export default AppLocalizations = {
    loginOrSignUp: 'loginOrSignUp',
    emailPlacehoder: 'emailPlacehoder',
    passwordPlaceholder: 'passwordPlaceholder',
    forgotPassword: 'forgotPassword',
    enterButton: 'enterButton',
    enterWithGoogle: 'enterWithGoogle',
    dontHaveAccount: 'dontHaveAccount',
    createAccount: 'createAccount',

    recoveryPassword: 'recoveryPassword',
    recoveryPasswordHint: 'recoveryPasswordHint',
    continueButton: 'continueButton',
    emailVerify: 'emailVerify',
    emailVerifyHint: 'emailVerifyHint',
    resentCode: 'resentCode',

    redefinePassword: 'redefinePassword',
    redefinePasswordHint: 'redefinePasswordHint',
    newPasswordPlaceHolder: 'newPasswordPlaceHolder',
    confirmNewPasswordPlaceHolder: 'confirmNewPasswordPlaceHolder',

    createAccountTitle: 'createAccountTitle',
    createAccountHint: 'createAccountHint',
    confirmPassword: 'confirmPassword',
    signUp: 'signUp',
    cancel: 'cancel',

    welcome: 'welcome',
    scheduled: 'scheduled',
    carriedOut: 'carriedOut',
    canceled: 'canceled',

    schedule: 'schedule',
    clinic: 'clinic',
    profile: 'profile',

    yearsOld: 'yearsOld',

    seeMedicalRecord: 'seeMedicalRecord',

    cancelExam: 'cancelExam',
    cancelExamHint: 'cancelExamHint',
    confirm: 'confirm',
    insertMedicalRecordButton: 'insertMedicalRecordButton',

    appointDescriptionLabel: 'appointDescriptionLabel',
    descriptionHint: 'descriptionHint',
    patientDiagnosisLabel: 'patientDiagnosisLabel',
    diagnosisLabel: 'diagnosisLabel',
    doctorPrescriptionLabel: 'doctorPrescriptionLabel',
    saveButton: 'saveButton',
    editButton: 'editButton',

    january: 'january',
    february: 'february',
    march: 'march',
    april: 'april',
    mayFull: 'mayFull',
    june: 'june',
    july: 'july',
    august: 'august',
    september: 'september',
    october: 'october',
    november: 'november',
    december: 'december',

    jan: 'jan',
    feb: 'feb',
    mar: 'mar',
    apr: 'apr',
    may: 'may',
    jun: 'jun',
    jul: 'jul',
    aug: 'aug',
    sep: 'sep',
    oct: 'oct',
    nov: 'nov',
    dec: 'dec',

    sunday: 'sunday',
    monday: 'monday',
    tuesday: 'tuesday',
    wednesday: 'wednesday',
    thursday: 'thursday',
    friday: 'friday',
    saturday: 'saturday',

    sun: 'sun',
    mon: 'mon',
    tue: 'tue',
    wed: 'wed',
    thu: 'thu',
    fri: 'fri',
    sat: 'sat',

    typeofAppointmentLabel: 'typeofAppointmentLabel',
    typeofAppointmentHint: 'typeofAppointmentHint',
    appointmenteLevelLabel: 'appointmenteLevelLabel',
    routine: 'routine',
    exam: 'exam',
    urgency: 'urgency',
    desiredLocationLabel: 'desiredLocationLabel',
    desiredLocationHint: 'desiredLocationHint',

    selectClinic: 'selectClinic',

    selectDoctor: 'selectDoctor',

    selectDate: 'selectDate',
    selectAvailableTimeLabel: 'selectAvailableTimeLabel',
    selectAvailableTimeHint: 'selectAvailableTimeHint',

    scheduleAppointment: 'scheduleAppointment',
    scheduleAppointmentHint: 'scheduleAppointmentHint',
    appoitmentDate: 'appoitmentDate',
    appoitmentDoctor: 'appoitmentDoctor',
    appointmentLocal: 'appointmentLocal',

    seeAppointmentLocal: 'seeAppointmentLocal',

    adress: 'adress',
    number: 'number',
    neighborhood: 'neighborhood',
    
    medicalExams: 'medicalExams',
    noPhotoReported: 'noPhotoReported',
    send: 'send',
    confirmPhoto: 'confirmPhoto',
    deleteImage: 'deleteImage',
    photoReported: 'photoReported',
    photosReported: 'photosReported',
    
    dateOfBirth: 'dateOfBirth',
    cpf: 'cpf',
    cep: 'cep',
    city: 'city',
    back: 'back',
    logOut: 'logOut'
}